Add CI task to push content to generated-sql branch
Fixes #1742

The
[`generated-sql`](https://github.com/mozilla/bigquery-etl/tree/generated-sql)
branch now exists and you can browse the contents. See, for example,
[telemetry.main](https://github.com/mozilla/bigquery-etl/tree/generated-sql/sql/moz-fx-data-shared-prod/telemetry/main)

Follow-ups for which I'll file issues:

- This doesn't currently publish the generated Glean baseline ETL queries
  and views; we'll need to update that logic to use probe-scraper metadata
  rather than listing tables in BigQuery (due to creds) to integrate it.
- Docs publishing should reference this generated content rather

diff --git a/script/generate_all_views b/script/generate_all_views
--- a/script/generate_all_views
+++ b/script/generate_all_views
@@ -23,11 +23,15 @@ case $key in
     shift # past argument
     shift # past value
     ;;
+    *)    # unknown option
+    echo "ERROR: Unknown option: $1" >&2
+    exit 1
+    ;;
 esac
 done
 
 # Fill in any missing view definitions in the moz-fx-data-shared-prod/ folder
-./script/generate_views "${TARGET_PROJECT}:*_stable.*" --sql-dir "${SQL_DIR}"
+python -m bigquery_etl.view.generate_stable_views --sql-dir "${SQL_DIR}" --parallelism=20
 
 # Fill in views for generated Glean ETL
 PLACEHOLDER_DATE="2000-01-01"
